# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  storage_resource_group_name: "template-grp"
  storage_account_name: "templatestorelirkov"
  container_name: "terraform"
  bK_storage_key: main.tfstate

stages:
  - stage: tfvalidate
    jobs:
      - job: validate
        continueOnError: false
        steps:
          - task: TerraformInstaller@1
            displayName: tfinstall
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            displayName: init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Visual Studio Enterprise Subscription – MPN (a9f6a84e-aa76-4493-ad46-7335d8bc7ea5)'
              backendAzureRmResourceGroupName: '$(storage_resource_group_name)'
              backendAzureRmStorageAccountName: '$(templatestorelirkov)'
              backendAzureRmContainerName: '$(terraform)'
              backendAzureRmKey: '$(main.tfstate)'
          - task: TerraformTaskV4@4
            displayName: validate
            inputs:
              provider: 'azurerm'
              command: 'validate'
  - stage: tfdeploy
    condition: succeeded('tfvalidate')
    dependsOn: tfvalidate
    jobs:
      - job: apply
        steps:
          - task: TerraformInstaller@1
            displayName: tfinstall
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            displayName: init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Visual Studio Enterprise Subscription – MPN (a9f6a84e-aa76-4493-ad46-7335d8bc7ea5)'
              backendAzureRmResourceGroupName: '$(storage_resource_group_name)'
              backendAzureRmStorageAccountName: '$(templatestorelirkov)'
              backendAzureRmContainerName: '$(terraform)'
              backendAzureRmKey: '$(main.tfstate)'
          - task: TerraformTaskV4@4
            displayName: plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'Visual Studio Enterprise Subscription – MPN (a9f6a84e-aa76-4493-ad46-7335d8bc7ea5)'
          - task: TerraformTaskV4@4
            displayName: apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'Visual Studio Enterprise Subscription – MPN (a9f6a84e-aa76-4493-ad46-7335d8bc7ea5)'